# This is all that needs to be changed when deploying to production
projects_url: http://dev

repository: https://github.com/smartpr/jquery.htmleditable.js
version: master
pygments: true
project_path: /jquery.htmleditable.js/_site