url: http://projects.smart.pr/jquery.htmleditable.js

pygments: true
repository: https://github.com/smartpr/jquery.htmleditable.js
version: master
theme: http://projects.smart.pr/project-site.themes/smartpr-oss.css
# theme: http://dev/project-site.themes/smartpr-oss.css
