#!/usr/bin/env sh

# Keep track of pids of launched processes so we can keep the house clean.
PIDS_FILE=`dirname $0`/.manage.pids

# Kill all processes that were spawned the last time this script executed.
if [ -f $PIDS_FILE ]; then
	kill -KILL `cat $PIDS_FILE`
	rm $PIDS_FILE
fi

case $1 in
dev)
	jekyll --auto --pygments --safe --url http://dev/jquery.htmleditable.js/gh-pages/_site &
	echo $! >> $PIDS_FILE
	compass watch --poll --environment development &
	echo $! >> $PIDS_FILE
	;;
release)
	# This is how GitHub runs jekyll.
	jekyll --pygments --safe
	compass compile --force --environment production
	git commit --all -m "Built for release"
	git push origin gh-pages
	;;
*)
	echo "Usage: manage [command]"
	echo ""
	echo "Commands:"
	echo "  dev       Build continuously"
	echo "  release   Build, commit, push and publish"
	echo "  *         Kill any running processes and display this description"
	echo ""
	echo "Dependencies: jekyll, compass, git"
	;;
esac
